language: java
git:
  depth: false
services:
  - mysql
env:
  - DB=mysql
before_script:
  - mkdir -p /home/travis/build/PERLUR/deploy
  - cp conf/conf_devel.properties ./conf_deploy.properties
script:
  - ant