language: java
sudo: true
git:
  depth: false
addons:
  apt:
    - ldap-utils
    - slapd
services:
  - mysql
before_script:
  - mkdir -p /home/travis/build/PERLUR/deploy
  - cp conf/conf_devel.properties ./conf_deploy.properties
  - sudo cp portal/conf/ldap/stickfish.schema /etc/openldap/schema
script:
  - ant