language: java
sudo: true
git:
  depth: false
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
services:
  - mysql
before_script:
  - ./bin/travis/import_test_db.sh
  - mkdir -p /home/travis/build/PERLUR/deploy
  - cp conf/conf_devel.properties ./conf_deploy.properties
  - sudo cp conf/ldap/stickfish.schema /etc/ldap/schema
  - sudo systemctl start slapd
install:
  - "" # Workaround till full migration to Maven
script:
  - ant